name: english_words
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"
english_words: ^3.1.5

dependencies:
  flutter:
    sdk: flutter
  # UI
  cupertino_icons: ^0.1.3
  quotes: 0.0.2

  # State Managment
  provider: ^4.3.2+2
  
 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  